<a href="https://colab.research.google.com/github/B-bori/Personal-python-practice/blob/master/Inverse_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
# 내 방법

import numpy as np 
from io import StringIO




''' Input matrix '''

print("##############################################")
print()
print("size of the matrix")
n = int(input())
print()

print("making a matrix; you shoud hit enter whenever you finish inputting row values")
M = ''
for i in range(n):
  M += input()
  M += '\n'

print()

M = StringIO(M)
M = np.loadtxt(M)




''' Determinant'''

def determinant(M):
  if(M.shape[0]==1):
    D = M[0]
    return D

  else:
    D = 0
    for i in range(M.shape[0]):
      for k in range(1,M.shape[0]):
        tmp = []
        for j in range(M.shape[0]):
          if (j!=i):
            tmp.append(M[k][j])
        tmp = np.array(tmp)
        if (k==1):
          ret = tmp
        else:
          ret = np.vstack([ret, tmp]) 
  
      if (i%2 == 0):
        D += M[0][i] * determinant(ret)
      else:
        D -= M[0][i] * determinant(ret)

    return D




''' Transpose matrix '''

def Transpose(M):
  M_transpose = []
  for row in range(M.shape[1]):
    M_transpose.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    for j in range(M.shape[1]):
      M_transpose[j][i] = M[i][j]
  
  M_transpose = np.array(M_transpose)

  return M_transpose




''' Inverse matrix '''

def Inverse(M):
  M_inv = []
  for row in range(M.shape[0]):
    M_inv.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    A = 0
    if (i==0):
      for j in range(M.shape[0]):
        
        for k in range(1,M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
          tmp = np.array(tmp)
        
          if (k==1):
            A = tmp
          else:
            A = np.vstack([A,tmp]) 
  
        M_inv[i][j] = (-1)**(i+j) * determinant(A)

    else:
      for j in range(M.shape[0]):        
        
        for k in range(0,i):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          if (k==0):
            A = tmp
          else:
            A = np.vstack([A,tmp])
    
        for k in range(i+1, M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          A = np.vstack([A,tmp])
    
        M_inv[i][j] = (-1)**(i+j) * determinant(A)
  
  M_inv = np.array(M_inv)
  return Transpose(M_inv) / determinant(M)

print(determinant(M))
print()
print(Inverse(M))
print()
print("built-in inverse matrix output")
print(np.linalg.inv(M))

##############################################

size of the matrix
4

making a matrix; you shoud hit enter whenever you finish inputting row values
5 1 7 1
2 4 1 7
6 1 4 3
8 2 4 1

381.0

[[-0.14435696 -0.06036745  0.1496063   0.11811024]
 [ 0.14173228  0.20472441 -0.63779528  0.33858268]
 [ 0.23622047  0.00787402 -0.06299213 -0.1023622 ]
 [-0.07349081  0.04199475  0.33070866 -0.21259843]]

built-in inverse matrix output
[[-0.14435696 -0.06036745  0.1496063   0.11811024]
 [ 0.14173228  0.20472441 -0.63779528  0.33858268]
 [ 0.23622047  0.00787402 -0.06299213 -0.1023622 ]
 [-0.07349081  0.04199475  0.33070866 -0.21259843]]


In [16]:
# 지홍이형 방법_ input 받는 부분만 내가 수정
# 근데 결과가 약간 다르게 나옴..... 수정이 필요할수도,,

import numpy as np
from io import StringIO




''' Input matrix '''

print("##############################################")
print()
print("size of the matrix")
n = int(input())
print()

print("making a matrix; you shoud hit enter whenever you finish inputting row values")
M = ''
for i in range(n):
  M += input()
  M += '\n'

print()

M = StringIO(M)
M = np.loadtxt(M)




def det(a):                                # det는 행렬식 (신발끈 정리 이용)
  n = a.shape[0]
  if n==2:
    return a[0][0]*a[1][1]-a[1][0]*a[0][1]
  else:
    sum1 = 0
    sum2 = 0
    for i in range(n):
      sum = 1
      for j in range(n):
        sum *= a[j][(i+j)%n]
      sum1 += sum
    for i in range(n):
      sum = 1
      for j in range(n):
        sum *= a[j][(n-1+i-j)%n]
      sum2 += sum
    return sum1-sum2




def T(a):                                  # T는 전치행렬
  k = a.shape[0]
  t_a = a
  for i in range(k):
    for j in range(k):
      t_a[i][j] = a[j][i]
  return t_a





def adj(a):                                # adj는 여인수행렬
  k = a.shape[0]
  
  if k==2:
    adj = np.array([[a[1][1],-1*a[1][0]],
                    [-1*a[0][1],a[0][0]]])
    return adj
  
  else:
    adj = []
    for i in range(k):
      m = np.vstack((a[:0,:], a[1:,:]))
      n = np.hstack((m[:,:i], m[:,i+1:]))
      d = det(n)
      adj.append(((-1)**(i))*d)
    adj = np.array(adj)
    for i in range(k):
      row = []
      for j in range(k):
        m = np.vstack((a[:i,:], a[i+1:,:]))
        n = np.hstack((m[:,:j], m[:,j+1:]))
        d = det(n)
        row.append(((-1)**(i+j))*d)
      adj = np.vstack((adj, np.array(row)))
    adj = adj[1:,:]
    adj = T(adj)
    return adj





def invf(a):                               # invf는 역행렬
  return (1/det(a))*adj(a)




print(det(M))
print()
print(invf(M))
print()
print("built-in inverse matrix output")
print(np.linalg.inv(M))

##############################################

size of the matrix
4

making a matrix; you shoud hit enter whenever you finish inputting row values
5 1 7 1
2 4 1 7
6 1 4 3
8 2 4 1

220.0

[[-0.25       -0.10454545  0.25909091  0.20454545]
 [-0.10454545  0.35454545 -1.10454545  0.58636364]
 [ 0.25909091 -1.10454545 -0.10909091 -0.17727273]
 [ 0.20454545  0.58636364 -0.17727273 -0.36818182]]

built-in inverse matrix output
[[-0.14435696 -0.06036745  0.1496063   0.11811024]
 [ 0.14173228  0.20472441 -0.63779528  0.33858268]
 [ 0.23622047  0.00787402 -0.06299213 -0.1023622 ]
 [-0.07349081  0.04199475  0.33070866 -0.21259843]]


In [17]:
# 동건이형 방법_ input 받는 부분만 내가 수정
# det, Transpose는 built-in 사용

import numpy as np
from io import StringIO




''' Input matrix '''

print("##############################################")
print()
print("size of the matrix")
n = int(input())
print()

print("making a matrix; you shoud hit enter whenever you finish inputting row values")
M = ''
for i in range(n):
  M += input()
  M += '\n'

print()

M = StringIO(M)
M = np.loadtxt(M)




def matrix_cofactor(matrix):
    A = np.zeros(matrix.shape)
    nrows, ncols = A.shape
    minor = np.zeros([nrows-1, ncols-1])
    for row in range(nrows):
      for col in range(ncols):
        minor[:row,:col] = matrix[:row,:col]
        minor[row:,:col] = matrix[row+1:,:col]
        minor[:row,col:] = matrix[:row,col+1:]
        minor[row:,col:] = matrix[row+1:,col+1:]
        A[row, col] = (-1)**(row+col) * np.linalg.det(minor)
    return A




def matrix_inverse(matrix):
  cofactor=matrix_cofactor(matrix)
  I= np.zeros(matrix.shape)
  nrows, ncols=I.shape
  for row in range(nrows):
    for col in range(ncols):
      I[row,col]= cofactor[row,col]/(np.linalg.det(matrix))
  return np.transpose(I)




print(np.linalg.det(M))
print()
print(matrix_inverse(M))
print()
print("built-in inverse matrix output")
print(np.linalg.inv(M))

##############################################

size of the matrix
4

making a matrix; you shoud hit enter whenever you finish inputting row values
5 1 7 1
2 4 1 7
6 1 4 3
8 2 4 1

381.0000000000001

[[-0.14435696 -0.06036745  0.1496063   0.11811024]
 [ 0.14173228  0.20472441 -0.63779528  0.33858268]
 [ 0.23622047  0.00787402 -0.06299213 -0.1023622 ]
 [-0.07349081  0.04199475  0.33070866 -0.21259843]]

built-in inverse matrix output
[[-0.14435696 -0.06036745  0.1496063   0.11811024]
 [ 0.14173228  0.20472441 -0.63779528  0.33858268]
 [ 0.23622047  0.00787402 -0.06299213 -0.1023622 ]
 [-0.07349081  0.04199475  0.33070866 -0.21259843]]
