<a href="https://colab.research.google.com/github/B-bori/Personal-python-practice/blob/master/Inverse_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
from io import StringIO




''' Input matrix '''

print("##############################################")
print()
print("size of the matrix")
n = int(input())
print()

print("making a matrix; you shoud hit enter whenever you finish inputting row values")
M = ''
for i in range(n):
  M += input()
  M += '\n'

print()

M = StringIO(M)
M = np.loadtxt(M)




''' Determinant'''

def determinant(M):
  if(M.shape[0]==1):
    D = M[0]
    return D

  else:
    D = 0
    for i in range(M.shape[0]):
      for k in range(1,M.shape[0]):
        tmp = []
        for j in range(M.shape[0]):
          if (j!=i):
            tmp.append(M[k][j])
        tmp = np.array(tmp)
        if (k==1):
          ret = tmp
        else:
          ret = np.vstack([ret, tmp]) 
  
      if (i%2 == 0):
        D += M[0][i] * determinant(ret)
      else:
        D -= M[0][i] * determinant(ret)

    return D




''' Transpose matrix '''

def Transpose(M):
  M_transpose = []
  for row in range(M.shape[1]):
    M_transpose.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    for j in range(M.shape[1]):
      M_transpose[j][i] = M[i][j]
  
  M_transpose = np.array(M_transpose)

  return M_transpose




''' Inverse matrix '''

def Inverse(M):
  M_inv = []
  for row in range(M.shape[0]):
    M_inv.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    A = 0
    if (i==0):
      for j in range(M.shape[0]):
        
        for k in range(1,M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
          tmp = np.array(tmp)
        
          if (k==1):
            A = tmp
          else:
            A = np.vstack([A,tmp]) 
  
        M_inv[i][j] = (-1)**(i+j) * determinant(A)

    else:
      for j in range(M.shape[0]):        
        
        for k in range(0,i):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          if (k==0):
            A = tmp
          else:
            A = np.vstack([A,tmp])
    
        for k in range(i+1, M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          A = np.vstack([A,tmp])
    
        M_inv[i][j] = (-1)**(i+j) * determinant(A)
  
  M_inv = np.array(M_inv)
  return Transpose(M_inv) / determinant(M)

print(Inverse(M))

##############################################

size of the matrix
5

making a matrix; you shoud hit enter whenever you finish inputting row values
1 5 4 2 2
3 7 2 5 1
2 6 7 1 2
7 5 2 4 1
3 6 2 4 1

[[-0.11111111 -0.66666667 -0.          0.11111111  0.77777778]
 [-0.44444444 -2.66666667  0.         -0.55555556  4.11111111]
 [-0.          2.33333333  0.33333333  0.33333333 -3.33333333]
 [ 0.44444444  3.66666667  0.          0.55555556 -5.11111111]
 [ 1.22222222 -1.33333333 -0.66666667  0.11111111  1.11111111]]
