In [132]:
from sympy import *
import numpy as np 
from io import StringIO

a = Symbol('a')

M = np.array([[2,0], [0,2]])

''' Identity matrix '''

I = [1]

for i in range(M.shape[0]-1):
  I.append(0)

for i in range(M.shape[0]-1):
  tmp = [0]
  for j in range(M.shape[0]-1):
    if (i==j):
      tmp.append(1)
    else:
      tmp.append(0)
  I = np.vstack([I,tmp])




''' Determinant'''

def determinant(M):
  if(M.shape[0]==1):
    D = M[0]
    return D

  else:
    D = 0
    for i in range(M.shape[0]):
      for k in range(1,M.shape[0]):
        tmp = []
        for j in range(M.shape[0]):
          if (j!=i):
            tmp.append(M[k][j])
        tmp = np.array(tmp)
        if (k==1):
          ret = tmp
        else:
          ret = np.vstack([ret, tmp]) 
  
      if (i%2 == 0):
        D += M[0][i] * determinant(ret)
      else:
        D -= M[0][i] * determinant(ret)

    return D




''' Inverse matrix '''

def Inverse(M):
  M_inv = []
  for row in range(M.shape[0]):
    M_inv.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    A = 0
    if (i==0):
      for j in range(M.shape[0]):
        
        for k in range(1,M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
          tmp = np.array(tmp)
        
          if (k==1):
            A = tmp
          else:
            A = np.vstack([A,tmp]) 
  
        M_inv[i][j] = (-1)**(i+j) * determinant(A)

    else:
      for j in range(M.shape[0]):        
        
        for k in range(0,i):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          if (k==0):
            A = tmp
          else:
            A = np.vstack([A,tmp])
    
        for k in range(i+1, M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          A = np.vstack([A,tmp])
    
        M_inv[i][j] = (-1)**(i+j) * determinant(A)
  
  M_inv = np.array(M_inv)
  return np.transpose(M_inv) / determinant(M)

M_modified = M + I * a

print(M)
print()
print(determinant(M))
print()
print(Inverse(M))
print()
print(M_modified)
print()
print(determinant(M_modified))
print()
print(Inverse(M_modified))

[[2 0]
 [0 2]]

4

[[0.5 0. ]
 [0.  0.5]]

[[a + 2 0]
 [0 a + 2]]

(a + 2)**2

[[1/(a + 2) 0]
 [0 1/(a + 2)]]


In [118]:
import numpy as np
from sympy import Symbol

a = Symbol('a')

a = np.array([[1,2],[3,a]])

print(a)
print(1/determinant(a))

[[1 2]
 [3 a]]
1/(a - 6)


In [110]:
import numpy as np

M = np.array([[1,2,3],[3,4,5],[5,6,7]])
M_inv = []
for row in range(M.shape[0]):
  M_inv.append([0]*M.shape[0])
print(M_inv)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [126]:
from sympy import *
import numpy as np 
from io import StringIO

a = Symbol('a')




''' Input matrix '''

print("##############################################")
print()
print("size of the matrix")
n = int(input())
print()

print("making a matrix; you shoud hit enter whenever you finish inputting row values")
M = ''
for i in range(n):
  M += input()
  M += '\n'

print()

M = StringIO(M)
M = np.loadtxt(M)
print("given matrix, M")
print(M)
print()




''' eigendecomposition '''

l, Q = np.linalg.eig(M)
L = np.diag(l)
Qinv = np.linalg.inv(Q)

print("##############################################")
print()
print("This following is eigendecomposition process")
print()
print('Q')
print(Q)
print()
print('L')
print(L)
print()
print("built-in Inverse matrix output of Q")
print(Qinv)
print("My Inverse matrix output of Q")
print(Inverse(Q))
print()
print("------------------ showing equivalence -----------------")
print("after eigendecomposition, assembled matrix")
print(Q.dot(L).dot(Qinv))



''' Determinant'''

def determinant(M):
  if(M.shape[0]==1):
    D = M[0]
    return D

  else:
    D = 0
    for i in range(M.shape[0]):
      for k in range(1,M.shape[0]):
        tmp = []
        for j in range(M.shape[0]):
          if (j!=i):
            tmp.append(M[k][j])
        tmp = np.array(tmp)
        if (k==1):
          ret = tmp
        else:
          ret = np.vstack([ret, tmp]) 
  
      if (i%2 == 0):
        D += M[0][i] * determinant(ret)
      else:
        D -= M[0][i] * determinant(ret)

    return D




''' Inverse matrix '''

def Inverse(M):
  M_inv = []
  for row in range(M.shape[0]):
    M_inv.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    A = 0
    if (i==0):
      for j in range(M.shape[0]):
        
        for k in range(1,M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
          tmp = np.array(tmp)
        
          if (k==1):
            A = tmp
          else:
            A = np.vstack([A,tmp]) 
  
        M_inv[i][j] = (-1)**(i+j) * determinant(A)

    else:
      for j in range(M.shape[0]):        
        
        for k in range(0,i):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          if (k==0):
            A = tmp
          else:
            A = np.vstack([A,tmp])
    
        for k in range(i+1, M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          A = np.vstack([A,tmp])
    
        M_inv[i][j] = (-1)**(i+j) * determinant(A)
  
  M_inv = np.array(M_inv)
  return np.transpose(M_inv) / determinant(M)


##############################################

size of the matrix
2

making a matrix; you shoud hit enter whenever you finish inputting row values
2 0
0 2

given matrix, M
[[2. 0.]
 [0. 2.]]

##############################################

This following is eigendecomposition process

Q
[[1. 0.]
 [0. 1.]]

L
[[2. 0.]
 [0. 2.]]

built-in Inverse matrix output of Q
[[1. 0.]
 [0. 1.]]
My Inverse matrix output of Q


SympifyError: ignored

In [134]:
from sympy import *
import numpy as np 
from io import StringIO

n = int(input())

M = ''
for i in range(n):
  M += input()
  M += '\n'

M = StringIO(M)
M = np.loadtxt(M)

''' eigendecomposition '''

l, Q = np.linalg.eig(M)
L = np.diag(l)
Qinv = np.linalg.inv(Q)

print(Q)
print()
print(determinant(Q))

2
2 0
0 2
[[1. 0.]
 [0. 1.]]

1.0


In [140]:
from sympy import *
import numpy as np

x = symbols("x")

#s = float(input())
s = 0.01

def f(x):
  return log(g(x))

def g(x):
  return np.e**h(x)

def h(x):
  return 2*x**2+k(x)

def k(x):
  return 5.0*x-1


prime = simplify(diff(f(x),x).subs(x,g(h(k(x))))*diff(g(x),x).subs(x,h(k(x)))*diff(h(x),x).subs(x,k(x))*diff(k(x),x))


def GD(t): 
  L = []
  for i in range(100):
    if(prime.subs(x,t) >= 0 and prime.subs(x,t-s) < 0):
      L.append(t)
      t = t - 1
    t = t - s
    
    else:
      t = t + s
  return L

#a = float(input())
a = float(input())
print(list(set(GD(a))))

SyntaxError: ignored

In [146]:
from sympy import *

x = Symbol('x')
f = 2*x**2 - 1
a, b = solve(f,x)
print(a)
print(b)

-sqrt(2)/2
sqrt(2)/2


In [3]:
import sympy as sp

x = sp.Symbol("x")

def f(x):
  return sp.log(g(x))

def g(x):
  return sp.exp(h(x))

def h(x):
  return 2*x**2+k(x)

def k(x):
  return 5*x-1

''' Derivative '''

def fd(x):
  return sp.diff(f(x),x)

def gd(x):
  return sp.diff(g(x),x)

def hd(x):
  return sp.diff(h(x),x)

def kd(x):
  return sp.diff(k(x),x)

prime = kd(h(x))

print(prime)

ValueError: ignored

In [11]:
import sympy as sp

x = sp.Symbol("x")


def h(x):
  return 2*x**2+k(x)

def k(x):
  return 5*x-1

''' Derivative '''

def hd(a):
  return sp.diff(h(x),x).subs(x,a)

def kd(x):
  return sp.diff(k(x),x)

prime = hd(2)

print(type(prime))
print(type(kd(x)))

<class 'sympy.core.numbers.Integer'>
<class 'sympy.core.numbers.Integer'>


In [12]:
#YOUR CODE OF QUESTION 10 SHOULD BE HERE 

from sympy import *
from numpy import array

n = int(input("n: "))
f = input("f: ")
print()
r = float(input("stepsize: ")) # r is stepsize
tol = float(input("tolerance: "))
print()

def gradient(f):
  array = [0]*n
  for i in range(n):
    array[i] = diff(f,Symbol('x'+str(i+1)))
  return array

def GD(f,r): 
  A = [0]*n
  B = [0]*n
  for i in range(n):
    A[i] = float(input("x"+str(i+1)+":"))
    B[i] = Symbol('x'+str(i+1))
  print()
  
  while True:
    
    cnt = 0

    for j in range(n):
      A[j] -= r * gradient(f)[j].subs(B[j],A[j])
      if (abs(r*gradient(f)[j].subs(B[j],A[j])) < tol):
        cnt += 1

    if (cnt==n):
      return A  
 
print(GD(f,r))

n: 3
f: (x1-2)**2 + (x2-3)**2 + (x3-1)**3

stepsize: 0.1
tolerance: 0.00001

x1:0
x2:-1
x3:2

[2.00000000000000, 3.00000000000000, 1.00577016976135]


In [17]:
x = 0.167 * 0.5

print(x)
print()
x = round(x,3)
print(x)

0.0835

0.084


In [22]:
import numpy as np

M = np.array([[1,2,3,4],[5,6,7,8]])
print(M)
print()

def Transpose(M):
  M_transpose = np.zeros([M.shape[1], M.shape[0]])
  
  for i in range(M.shape[0]):
    for j in range(M.shape[1]):
      M_transpose[j][i] = M[i][j]
  
  return M_transpose

print(Transpose(M))

[[1 2 3 4]
 [5 6 7 8]]

[[1. 5.]
 [2. 6.]
 [3. 7.]
 [4. 8.]]


In [18]:
import numpy as np

a = np.array([[1,2],[3,4]])

print(a)
print()
a = a.reshape(4,1)
print(a)

[[1 2]
 [3 4]]

[[1]
 [2]
 [3]
 [4]]


In [25]:
import numpy as np 
from io import StringIO




''' Input matrix '''

print("##############################################")
print()
print("size of the matrix")
n = int(input())
print()

print("making a matrix; you shoud hit enter whenever you finish inputting row values")
M = ''
for i in range(n):
  M += input()
  M += '\n'

print()

M = StringIO(M)
M = np.loadtxt(M)




''' Determinant'''

def determinant(M):
  if(M.shape[0]==1):
    D = M[0]
    return D

  else:
    D = 0
    for i in range(M.shape[0]):
      for k in range(1,M.shape[0]):
        tmp = []
        for j in range(M.shape[0]):
          if (j!=i):
            tmp.append(M[k][j])
        tmp = np.array(tmp)
        if (k==1):
          ret = tmp
        else:
          ret = np.vstack([ret, tmp]) 
  
      if (i%2 == 0):
        D += M[0][i] * determinant(ret)
      else:
        D -= M[0][i] * determinant(ret)

    return D




''' Transpose matrix '''

def Transpose(M):
  M_transpose = []
  for row in range(M.shape[1]):
    M_transpose.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    for j in range(M.shape[1]):
      M_transpose[j][i] = M[i][j]
  
  M_transpose = np.array(M_transpose)

  return M_transpose




''' Inverse matrix '''

def Inverse(M):
  M_inv = []
  for row in range(M.shape[0]):
    M_inv.append([0]*M.shape[0])

  for i in range(M.shape[0]):
    A = 0
    if (i==0):
      for j in range(M.shape[0]):
        
        for k in range(1,M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
          tmp = np.array(tmp)
        
          if (k==1):
            A = tmp
          else:
            A = np.vstack([A,tmp]) 
  
        M_inv[i][j] = (-1)**(i+j) * determinant(A)

    else:
      for j in range(M.shape[0]):        
        
        for k in range(0,i):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          if (k==0):
            A = tmp
          else:
            A = np.vstack([A,tmp])
    
        for k in range(i+1, M.shape[0]):
          tmp = []
          for l in range(M.shape[0]):
            if (l!=j):
              tmp.append(M[k][l])
      
          tmp = np.array(tmp)
          A = np.vstack([A,tmp])
    
        M_inv[i][j] = (-1)**(i+j) * determinant(A)
  
  M_inv = np.array(M_inv)
  return Transpose(M_inv) / determinant(M)

print(Inverse(M))

##############################################

size of the matrix
5

making a matrix; you shoud hit enter whenever you finish inputting row values
1 5 4 2 2
3 7 2 5 1
2 6 7 1 2
7 5 2 4 1
3 6 2 4 1

[[-0.11111111 -0.66666667 -0.          0.11111111  0.77777778]
 [-0.44444444 -2.66666667  0.         -0.55555556  4.11111111]
 [-0.          2.33333333  0.33333333  0.33333333 -3.33333333]
 [ 0.44444444  3.66666667  0.          0.55555556 -5.11111111]
 [ 1.22222222 -1.33333333 -0.66666667  0.11111111  1.11111111]]
